chuy = float(input('Enter the temperature for area chuy:'))
talas = float(input('enter the temperature for area talas:'))
batken = float(input('enter the temperature for area batken:'))
toktogul = float(input('enter the temperature for area toktogul:'))
osh = float(input('enter the temperature for osh area:'))
naryn = float(input('enter the temperature for naryn:'))
yssykkol = float(input('enter the temperature for yssykkol:'))
avarage = round((chuy+talas+batken+toktogul+osh+naryn+yssykkol)/7, 1)
print(f'Средний показатель температуры воздуха по КР на сегодня: {avarage}°C')
